export const TOOL_TO_TUI: Record<string, string> = {
  brightness: "brightness",
  contrast: "contrast",
  saturation: "saturation",
  blur: "blur",
  sharpen: "sharpen",
  noise: "noise",
  pixelate: "pixelate",
  invert: "invert",
  grayscale: "grayscale",
  sepia: "sepia",
  sepia2: "sepia2",
  removewhite: "removeWhite",
  emboss: "emboss",
  removeWhite: "removeWhite",
  colorfilter: "colorFilter",
  colorFilter: "colorFilter",
};
